### ISSUE TITLE
Implement aws region detection provider chain

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#204]
Define region detection (provider) chain, implement, and integration into: [regionDetection](https://github.com/awslabs/aws-sdk-kotlin/blob/v0.2.0-M1/client-runtime/regions/common/src/aws/sdk/kotlin/runtime/regions/AwsRegion.kt#L23)

NOTE: region detection function should probably migrate to a `suspend` function
Depends on:
- [x] awslabs/smithy-kotlin#356 - environment based detection
- [x] awslabs/aws-sdk-kotlin#202 - system property based detection (jvm)
- [x] awslabs/aws-sdk-kotlin#203 - profile based detection
- [x] awslabs/aws-sdk-kotlin#201 - ec2 metadata based detection
